version: "2"
services:
  mysql:
    image: mysql:5.5
    ports:
      - "3306"
    expose:
      - 3006
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: dev
      MYSQL_PASSWORD: root

  php:
    build: ./docker/php
    volumes:
      - ./code:/var/www/laravel/code
    links:
      - mysql
  
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php